### PR TITLE
Use Flash-based EEPROM on SKR Mini E3

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Add flash-based EEPROM support to the SKR Mini E3.

### Benefits

Users no longer have to use an SD card to store EEPROM settings.

### Related Issues

None.

### CODE REVIEW

**Comment by brew99** [comment]
Not sure how you are proposing to have this added, but if it is anything similar to what was discussed on the r/BIGTREETECH sub reddit, then I believe it will require some more testing.  It worked fine for me, but I couldn’t have the TMC_DEBUG enabled at the same time.

Would like to hear if this same thing happens to others?

**Comment by thisiskeithb** [comment]
> Not sure how you are proposing to have this added, but if it is anything similar to what was discussed on the r/BIGTREETECH sub reddit, then I believe it will require some more testing.

It's the same that's used on all the SKR Mini boards upstream in the main Marlin branch. I only see [your comment](https://www.reddit.com/r/BIGTREETECH/comments/cskfe2/skr_mini_e3_eeprom_settings/exvbhi7/)/no other discussion with users have issues, but there's been several reports of success with this in the various BigTreeTech Facebook groups.

If more reports come out/it really is an issue, than the `SanityCheck.h` can be updated to warn users to not have both options enabled.

**Comment by fluppie** [comment]
I tried #define EEPROM_AUTO_INIT but for me this doesn't work on a v1.2 board with soldered TMC2209's. So I cannot save the Z offset...

**Comment by Thinkersbluff** [comment]
I am having trouble with the Flash EEPROM and wonder whether I have configured it incorrectly.
I am using Manual Bed Leveling, with LCD.
If I use "Store Settings" on the "Bed Leveling" menu, before I power-off, then the mesh, fade height, etc. are restored on Power Up, but "Bed Leveling On/Off defaults to "Off", even if it was "On" when I stored settings.
If I fail to use "Store Settings" before power-off, then the mesh, fade height, etc. are "gone", next time I power on.  Is the Flash EEPROM only meant to last one power cycle & not persist over multiple power cycles??

**Comment by PizzaRoll04** [comment]
I am also having issues with this and would really be grateful to anyone who knows how to fix this.

**Pull request merged**
